-- ============================================================
--  SQL INSERT STATEMENTS FOR HANA DATABASE EXPLORER
--
--  HOW TO USE:
--  1. Open HANA Database Explorer
--  2. Connect to your schema
--  3. Open a new SQL Console
--  4. Copy-paste each block below and click Run (F8)
--  5. Run them IN ORDER (master tables first, then fact tables)
--
--  NOTE: The table names in HANA will be generated by CAP
--  in this format:  CIB_FINANCIALS_ENTITYNAME
--  e.g. ClusterMaster → CIB_FINANCIALS_CLUSTERMASTER
-- ============================================================


-- ============================================================
--  STEP 1: CLUSTER MASTER
--  Run this first — other tables reference clusterCode
-- ============================================================

INSERT INTO "CIB_FINANCIALS_CLUSTERMASTER"
    ("CLUSTERCODE", "CLUSTERNAME", "REGION", "SORTORDER")
VALUES
    ('AU',       'Australia',       'Asia Pacific', 1),
    ('AM',       'Americas',        'Americas',     2),
    ('AVE',      'Africa & Middle East', 'EMEA',    3),
    ('Asia',     'Asia',            'Asia Pacific', 4),
    ('EU',       'Europe',          'EMEA',         5),
    ('Unmapped', 'Unmapped',        'Unknown',      6);


-- ============================================================
--  STEP 2: PRODUCT MASTER
-- ============================================================

INSERT INTO "CIB_FINANCIALS_PRODUCTMASTER"
    ("PRODUCTCODE", "PRODUCTNAME", "CATEGORY", "SORTORDER")
VALUES
    ('TXSV', 'Transaction Services', 'Banking',  1),
    ('MKTS', 'Markets',              'Markets',  2),
    ('LEND', 'Lending',              'Banking',  3),
    ('TRFI', 'Trade Finance',        'Banking',  4),
    ('CASH', 'Cash Management',      'Banking',  5),
    ('CORP', 'Corporate Finance',    'Advisory', 6);


-- ============================================================
--  STEP 3: SEGMENT MASTER
-- ============================================================

INSERT INTO "CIB_FINANCIALS_SEGMENTMASTER"
    ("SEGMENTCODE", "SEGMENTNAME", "DESCRIPTION")
VALUES
    ('Sm',  'Small',               'Small Business Segment'),
    ('Sin', 'Single',              'Single Name Corporate'),
    ('Sen', 'Senior',              'Senior Corporate Segment'),
    ('GTX', 'Global Transaction',  'Global Transaction Banking');


-- ============================================================
--  STEP 4: REPORTING PERIOD MASTER
--  isCurrent = TRUE means this period loads by default
-- ============================================================

INSERT INTO "CIB_FINANCIALS_REPORTINGPERIODMASTER"
    ("PERIODKEY", "PERIODNAME", "FISCALYEAR", "QUARTER",
     "STARTDATE", "ENDDATE", "ISCURRENT")
VALUES
    ('2025-Q1', 'Q1 2025', '2025', 'Q1', '2025-01-01', '2025-03-31', FALSE),
    ('2025-Q2', 'Q2 2025', '2025', 'Q2', '2025-04-01', '2025-06-30', FALSE),
    ('2025-Q3', 'Q3 2025', '2025', 'Q3', '2025-07-01', '2025-09-30', TRUE),
    ('2025-Q4', 'Q4 2025', '2025', 'Q4', '2025-10-01', '2025-12-31', FALSE),
    ('2024-Q3', 'Q3 2024', '2024', 'Q3', '2024-07-01', '2024-09-30', FALSE),
    ('2024-Q4', 'Q4 2024', '2024', 'Q4', '2024-10-01', '2024-12-31', FALSE);


-- ============================================================
--  STEP 5: KPI SNAPSHOT
--
--  This is the main data for the dashboard header tiles.
--  Values are in BILLIONS (matching what's on your dashboard).
--  One row per period + segment combination.
--
--  Reading the numbers from your dashboard images:
--    Income:            9.01
--    NII:               0.96   (+135.82% vs prior year)
--    CIR:               47.01  (-15.83%)
--    ROTE:              25.55  (+131.04%)
--    RWA:               183.00 (+87.72%)
--    Underlying Profit: 4.64   (+2.08%)
--    Impairments:       -0.01  (+166.16%)
--    Funded Assets:     423.87 (+85.48%)
--    Costs:             4.24   (+75.28%)
--    Head Count:        +0.00  (+PA.53%)
-- ============================================================

INSERT INTO "CIB_FINANCIALS_KPISNAPSHOT" (
    "ID", "PERIODKEY", "SEGMENTCODE",

    "INCOME_YTD",    "INCOME_FYBUDGET",    "INCOME_FYOUTLOOK",
    "INCOME_PCTVSBUDGET", "INCOME_PCTVSPRIORYEAR",

    "NII_YTD",       "NII_FYBUDGET",       "NII_FYOUTLOOK",
    "NII_PCTVSBUDGET", "NII_PCTVSPRIORYEAR",

    "CIR_YTD",       "CIR_FYBUDGET",       "CIR_FYOUTLOOK",
    "CIR_PCTCHANGE",

    "JAWS_YTD",      "JAWS_FYBUDGET",      "JAWS_FYOUTLOOK",

    "COSTS_YTD",     "COSTS_FYBUDGET",     "COSTS_FYOUTLOOK",
    "COSTS_PCTVSBUDGET", "COSTS_PCTVSPRIORYEAR",

    "HEADCOUNT_ACTUAL", "HEADCOUNT_BUDGET", "HEADCOUNT_PCTCHANGE",

    "ROTE_YTD",      "ROTE_FYBUDGET",      "ROTE_FYOUTLOOK",
    "ROTE_PCTCHANGE",

    "RWA_ACTUAL",    "RWA_BUDGET",         "RWA_OUTLOOK",
    "RWA_PCTCHANGE",

    "UNDERLYINGPROFIT_YTD",    "UNDERLYINGPROFIT_BUDGET",
    "UNDERLYINGPROFIT_OUTLOOK","UNDERLYINGPROFIT_PCTCHG",

    "IMPAIRMENTS_YTD",    "IMPAIRMENTS_BUDGET",
    "IMPAIRMENTS_OUTLOOK","IMPAIRMENTS_PCTCHG",

    "FUNDEDASSETS_ACTUAL",  "FUNDEDASSETS_BUDGET",
    "FUNDEDASSETS_OUTLOOK", "FUNDEDASSETS_PCTCHG"
)
VALUES
-- Row 1: Q3 2025 | Segment: Sm  (matches your dashboard screenshot)
(1, '2025-Q3', 'Sm',
 9.01, 10.50, 10.20,  14.19, 12.45,
 0.96,  1.10,  1.05,  12.73, 135.82,
 47.01, 52.00, 49.50, -15.83,
 -1.00, -0.50, -0.80,
 4.24, 4.80, 4.60,   11.67, 75.28,
 47.01, 54.55, 0.00,
 25.55, 20.00, 22.50, 131.04,
 183.00, 195.00, 188.00, 87.72,
 4.64, 4.50, 4.80,   2.08,
 -0.01, -0.05, -0.03, 166.16,
 423.87, 450.00, 435.00, 85.48),

-- Row 2: Q3 2025 | Segment: Sin
(2, '2025-Q3', 'Sin',
 8.50, 9.80, 9.60,   13.27, 11.20,
 0.85, 0.95, 0.92,   10.53, 120.00,
 45.20, 50.50, 48.00, -10.50,
 -0.80, -0.40, -0.65,
 3.85, 4.20, 4.10,   8.33, 65.50,
 44.20, 51.00, 0.00,
 22.30, 18.50, 20.00, 120.54,
 175.00, 185.00, 180.00, 5.71,
 4.20, 4.10, 4.40,   2.44,
 -0.02, -0.06, -0.04, 133.33,
 410.50, 435.00, 420.00, 80.25),

-- Row 3: Q3 2025 | Segment: Sen
(3, '2025-Q3', 'Sen',
 7.80, 9.00, 8.80,   13.33, 10.14,
 0.78, 0.90, 0.88,   10.26, 115.38,
 44.50, 49.00, 47.50, -9.18,
 -0.60, -0.30, -0.55,
 3.50, 3.95, 3.80,   11.39, 60.75,
 43.50, 49.50, 0.00,
 20.15, 17.00, 19.00, 118.53,
 168.00, 178.00, 173.00, 5.62,
 3.85, 3.75, 4.00,   2.67,
 -0.01, -0.04, -0.03, 150.00,
 398.20, 420.00, 408.00, 78.40),

-- Row 4: Q3 2025 | Segment: GTX
(4, '2025-Q3', 'GTX',
 10.50, 12.00, 11.75, 12.50, 15.38,
 1.10, 1.25, 1.20,   12.00, 148.00,
 46.00, 51.00, 49.00, -9.80,
 -1.20, -0.65, -0.95,
 4.83, 5.50, 5.30,   12.18, 80.50,
 51.50, 58.00, 0.00,
 28.75, 23.50, 25.80, 140.43,
 195.00, 208.00, 200.00, 6.67,
 5.30, 5.15, 5.50,   2.91,
 -0.01, -0.05, -0.03, 133.33,
 445.00, 475.00, 458.00, 90.20),

-- Row 5: Q3 2024 | Segment: Sm  (prior year comparison)
(5, '2024-Q3', 'Sm',
 8.10, 9.50, 9.20,   14.74, 0.00,
 0.82, 0.98, 0.94,   16.34, 0.00,
 50.30, 53.00, 50.00, 0.00,
 0.50, 0.20, 0.30,
 3.85, 4.35, 4.20,   11.49, 0.00,
 45.00, 52.00, 0.00,
 19.50, 18.00, 20.00, 0.00,
 165.00, 178.00, 170.00, 0.00,
 4.20, 4.00, 4.35,   0.00,
 -0.03, -0.07, -0.05, 0.00,
 380.00, 405.00, 392.00, 0.00);


-- ============================================================
--  STEP 6: INCOME BY CLUSTER
--
--  This data powers the "Income By Cluster" TABLE.
--  One row = one cluster for one period + segment.
--
--  Numbers visible from your dashboard (Q3 2025, Sm):
--    AU:       ytd ~ 9,009,164,726
--    AM:       ytd ~ 831,906,982
--    AVE:      ytd ~ 470,256,344
--    Asia:     ytd ~ 1,610,395,800
--    EU:       ytd ~ 293,387,350
--    Unmapped: ytd ~ 50,291
-- ============================================================

INSERT INTO "CIB_FINANCIALS_INCOMEBYCLUSTER"
    ("ID", "PERIODKEY", "SEGMENTCODE", "CLUSTERCODE",
     "FYBUDGET", "YTDACTUAL", "Q3Q4OUTLOOK",
     "FYOUTLOOK", "WOWPCT", "YTDVSBUDGETPCT")
VALUES
-- Q3 2025 | Sm
(1,  '2025-Q3', 'Sm', 'AU',       9609164726.23, 9009164726.23, 2713883171.48, 54573025422.50,  1.48,  6.24),
(2,  '2025-Q3', 'Sm', 'AM',        891906982.13,  831906982.13,  333843810.14,  5593698554.30, -3.70,  6.73),
(3,  '2025-Q3', 'Sm', 'AVE',       475448450.18,  470256344.18,  670256344.18, 25420448982.25, 65.44,  1.09),
(4,  '2025-Q3', 'Sm', 'Asia',     1310395800.00, 1610395800.00, 1610395800.00, 50021117237.05, -4.48, 18.62),
(5,  '2025-Q3', 'Sm', 'EU',        295387350.85,  293387350.85,  293387350.85,  9542728256.00,189.17,  0.68),
(6,  '2025-Q3', 'Sm', 'Unmapped',      50291.05,      50291.05,      50291.05,      50291.05,  1.44,  0.00),

-- Q3 2025 | Sin
(7,  '2025-Q3', 'Sin', 'AU',      8950000000.00, 8420000000.00, 2650000000.00, 52100000000.00,  1.20,  5.92),
(8,  '2025-Q3', 'Sin', 'AM',       820000000.00,  775000000.00,  310000000.00,  5250000000.00, -3.10,  5.49),
(9,  '2025-Q3', 'Sin', 'AVE',      440000000.00,  435000000.00,  620000000.00, 24500000000.00, 55.20,  1.14),
(10, '2025-Q3', 'Sin', 'Asia',    1200000000.00, 1510000000.00, 1510000000.00, 47500000000.00, -4.10, 20.58),
(11, '2025-Q3', 'Sin', 'EU',       275000000.00,  272000000.00,  272000000.00,  9100000000.00,175.40,  1.09),
(12, '2025-Q3', 'Sin', 'Unmapped',     45000.00,      45000.00,      45000.00,      45000.00,  0.80,  0.00),

-- Q3 2025 | Sen
(13, '2025-Q3', 'Sen', 'AU',      8200000000.00, 7800000000.00, 2450000000.00, 49500000000.00,  1.10,  4.88),
(14, '2025-Q3', 'Sen', 'AM',       760000000.00,  720000000.00,  290000000.00,  4900000000.00, -2.80,  5.26),
(15, '2025-Q3', 'Sen', 'AVE',      410000000.00,  405000000.00,  590000000.00, 23200000000.00, 48.50,  1.22),
(16, '2025-Q3', 'Sen', 'Asia',    1100000000.00, 1400000000.00, 1400000000.00, 45000000000.00, -3.90, 21.43),
(17, '2025-Q3', 'Sen', 'EU',       255000000.00,  250000000.00,  250000000.00,  8600000000.00,165.20,  2.00),
(18, '2025-Q3', 'Sen', 'Unmapped',     40000.00,      40000.00,      40000.00,      40000.00,  0.50,  0.00),

-- Q3 2025 | GTX
(19, '2025-Q3', 'GTX', 'AU',     11200000000.00,10500000000.00, 3100000000.00, 62000000000.00,  1.80,  6.25),
(20, '2025-Q3', 'GTX', 'AM',      1050000000.00,  990000000.00,  380000000.00,  6300000000.00, -4.20,  5.71),
(21, '2025-Q3', 'GTX', 'AVE',      525000000.00,  520000000.00,  755000000.00, 28500000000.00, 72.30,  0.96),
(22, '2025-Q3', 'GTX', 'Asia',    1550000000.00, 1850000000.00, 1850000000.00, 58000000000.00, -5.10, 19.30),
(23, '2025-Q3', 'GTX', 'EU',       340000000.00,  335000000.00,  335000000.00, 11200000000.00,205.60,  1.49),
(24, '2025-Q3', 'GTX', 'Unmapped',     62000.00,      62000.00,      62000.00,      62000.00,  1.90,  0.00),

-- Q3 2024 | Sm  (prior year data)
(25, '2024-Q3', 'Sm', 'AU',       8900000000.00, 8300000000.00, 2400000000.00, 50000000000.00,  1.10,  6.76),
(26, '2024-Q3', 'Sm', 'AM',        820000000.00,  765000000.00,  285000000.00,  5100000000.00, -3.20,  6.54),
(27, '2024-Q3', 'Sm', 'AVE',       440000000.00,  430000000.00,  605000000.00, 23000000000.00, 58.00,  2.27),
(28, '2024-Q3', 'Sm', 'Asia',     1200000000.00, 1490000000.00, 1490000000.00, 46000000000.00, -4.10, 19.38),
(29, '2024-Q3', 'Sm', 'EU',        275000000.00,  270000000.00,  270000000.00,  8900000000.00,170.50,  1.82),
(30, '2024-Q3', 'Sm', 'Unmapped',      46500.00,      46500.00,      46500.00,      46500.00,  0.00,  0.00);


-- ============================================================
--  STEP 7: INCOME BY PRODUCT
--
--  This data powers the "Income By Product" BAR CHART.
--  One row = one product for one period + segment.
--
--  Visible bar values from your dashboard:
--    TXSV: ~10,829,997,999
--    MKTS: ~5,223,999,999
--    LEND: ~6,101,995,637
--    TRFI: ~2,153,306,530
-- ============================================================

INSERT INTO "CIB_FINANCIALS_INCOMEBYPRODUCT"
    ("ID", "PERIODKEY", "SEGMENTCODE", "PRODUCTCODE",
     "FYBUDGET", "YTDACTUAL", "Q3Q4OUTLOOK", "FYOUTLOOK", "WOWPCT")
VALUES
-- Q3 2025 | Sm
(1,  '2025-Q3', 'Sm', 'TXSV', 10829997999.43,  9850000000.00, 3150000000.00, 55000000000.00,  2.50),
(2,  '2025-Q3', 'Sm', 'MKTS',  5223999999.00,  4890000000.00, 1580000000.00, 28000000000.00,  1.80),
(3,  '2025-Q3', 'Sm', 'LEND',  6101995637.35,  5520000000.00, 1790000000.00, 31500000000.00, -2.10),
(4,  '2025-Q3', 'Sm', 'TRFI',  2153306530.95,  1980000000.00,  640000000.00, 11200000000.00,  3.20),
(5,  '2025-Q3', 'Sm', 'CASH',  3850000000.00,  3500000000.00, 1120000000.00, 19800000000.00,  1.50),
(6,  '2025-Q3', 'Sm', 'CORP',  1950000000.00,  1750000000.00,  560000000.00,  9900000000.00, -1.20),

-- Q3 2025 | Sin
(7,  '2025-Q3', 'Sin', 'TXSV', 9850000000.00,  9150000000.00, 2950000000.00, 52000000000.00,  2.20),
(8,  '2025-Q3', 'Sin', 'MKTS', 4900000000.00,  4580000000.00, 1480000000.00, 26500000000.00,  1.60),
(9,  '2025-Q3', 'Sin', 'LEND', 5750000000.00,  5200000000.00, 1680000000.00, 29800000000.00, -1.90),
(10, '2025-Q3', 'Sin', 'TRFI', 2000000000.00,  1850000000.00,  600000000.00, 10500000000.00,  2.90),
(11, '2025-Q3', 'Sin', 'CASH', 3600000000.00,  3280000000.00, 1050000000.00, 18600000000.00,  1.30),
(12, '2025-Q3', 'Sin', 'CORP', 1820000000.00,  1640000000.00,  525000000.00,  9300000000.00, -1.00),

-- Q3 2025 | Sen
(13, '2025-Q3', 'Sen', 'TXSV', 9100000000.00,  8500000000.00, 2750000000.00, 48500000000.00,  2.00),
(14, '2025-Q3', 'Sen', 'MKTS', 4550000000.00,  4250000000.00, 1380000000.00, 24800000000.00,  1.40),
(15, '2025-Q3', 'Sen', 'LEND', 5350000000.00,  4850000000.00, 1580000000.00, 27800000000.00, -1.70),
(16, '2025-Q3', 'Sen', 'TRFI', 1860000000.00,  1720000000.00,  560000000.00,  9800000000.00,  2.60),
(17, '2025-Q3', 'Sen', 'CASH', 3350000000.00,  3050000000.00,  980000000.00, 17400000000.00,  1.20),
(18, '2025-Q3', 'Sen', 'CORP', 1700000000.00,  1530000000.00,  492000000.00,  8700000000.00, -0.90),

-- Q3 2025 | GTX
(19, '2025-Q3', 'GTX', 'TXSV',12500000000.00, 11600000000.00, 3720000000.00, 65000000000.00,  2.80),
(20, '2025-Q3', 'GTX', 'MKTS', 5950000000.00,  5580000000.00, 1790000000.00, 32500000000.00,  2.10),
(21, '2025-Q3', 'GTX', 'LEND', 7000000000.00,  6350000000.00, 2050000000.00, 36000000000.00, -2.40),
(22, '2025-Q3', 'GTX', 'TRFI', 2450000000.00,  2250000000.00,  720000000.00, 12800000000.00,  3.50),
(23, '2025-Q3', 'GTX', 'CASH', 4450000000.00,  4050000000.00, 1290000000.00, 23000000000.00,  1.70),
(24, '2025-Q3', 'GTX', 'CORP', 2250000000.00,  2020000000.00,  645000000.00, 11500000000.00, -1.40),

-- Q3 2024 | Sm  (prior year comparison)
(25, '2024-Q3', 'Sm', 'TXSV',  9950000000.00,  8920000000.00, 2850000000.00, 50000000000.00,  2.10),
(26, '2024-Q3', 'Sm', 'MKTS',  4800000000.00,  4450000000.00, 1430000000.00, 25500000000.00,  1.60),
(27, '2024-Q3', 'Sm', 'LEND',  5600000000.00,  5000000000.00, 1620000000.00, 28500000000.00, -1.80),
(28, '2024-Q3', 'Sm', 'TRFI',  1990000000.00,  1800000000.00,  582000000.00, 10200000000.00,  2.80),
(29, '2024-Q3', 'Sm', 'CASH',  3550000000.00,  3180000000.00, 1020000000.00, 18000000000.00,  1.30),
(30, '2024-Q3', 'Sm', 'CORP',  1800000000.00,  1600000000.00,  512000000.00,  9100000000.00, -1.00);


-- ============================================================
--  VERIFY: Run these SELECT statements after inserting
--  to confirm everything loaded correctly
-- ============================================================

SELECT COUNT(*) AS "ClusterMaster Rows"        FROM "CIB_FINANCIALS_CLUSTERMASTER";
SELECT COUNT(*) AS "ProductMaster Rows"         FROM "CIB_FINANCIALS_PRODUCTMASTER";
SELECT COUNT(*) AS "SegmentMaster Rows"         FROM "CIB_FINANCIALS_SEGMENTMASTER";
SELECT COUNT(*) AS "ReportingPeriodMaster Rows" FROM "CIB_FINANCIALS_REPORTINGPERIODMASTER";
SELECT COUNT(*) AS "KPISnapshot Rows"           FROM "CIB_FINANCIALS_KPISNAPSHOT";
SELECT COUNT(*) AS "IncomeByCluster Rows"       FROM "CIB_FINANCIALS_INCOMEBYCLUSTER";
SELECT COUNT(*) AS "IncomeByProduct Rows"       FROM "CIB_FINANCIALS_INCOMEBYPRODUCT";
