-- ============================================================
-- ReportingMaster: UPDATE 12 widgets + INSERT 2 new chart widgets
-- Run each block separately in HANA Database Explorer
-- All  inside SQL strings are escaped as double quotes (HANA standard)
-- NOTE: Hardcoded filter dates like 2025-08-01 replaced with CURRENT_MONTH
-- ============================================================

-- ── UPDATE ID=1: Income ────────────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH
  FYoutlook_rfx AS (
    SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''CY''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  PYFYoutlook_rfx AS (
    SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''PY''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  FYoutlook_cfx AS (
    SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''CY''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  PYFYoutlook_cfx AS (
    SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''PY''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  PQTDactuals_rfx AS (
    SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -1 AND alldata.T_VERSION = ''QTD''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  PYPQTDactuals_rfx AS (
    SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''MTD''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  PQTDactuals_cfx AS (
    SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -1 AND alldata.T_VERSION = ''QTD''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  PYPQTDactuals_cfx AS (
    SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''MTD''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  YTDactuals_rfx AS (
    SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD16 = 0 AND alldata.T_VERSION = ''YTD''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  PYYTDactuals_rfx AS (
    SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  YTDactuals_cfx AS (
    SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD16 = 0 AND alldata.T_VERSION = ''YTD''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  ),
  PYYTDactuals_cfx AS (
    SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
    INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
    WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD''
      AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  )
SELECT
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) AS YTD_ACTUALS_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) AS YTD_ACTUALS_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END)
  - SUM(CASE WHEN alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) AS VS_BUDGET_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END)
  - SUM(CASE WHEN alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) AS VS_BUDGET_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1 THEN alldata.RFX ELSE 0 END) AS PQTD_ACTUALS_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1 THEN alldata.CFX ELSE 0 END) AS PQTD_ACTUALS_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'' THEN alldata.RFX ELSE 0 END) AS FY_OUTLOOK_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'' THEN alldata.CFX ELSE 0 END) AS FY_OUTLOOK_CFX_FPNA,
  CASE WHEN (SELECT val FROM PYFYoutlook_rfx) != 0 THEN ((SELECT val FROM FYoutlook_rfx) - (SELECT val FROM PYFYoutlook_rfx)) / ABS((SELECT val FROM PYFYoutlook_rfx)) * 100 ELSE NULL END AS VARIANCE_PYFY_OUTLOOK_RFX_FPNA,
  CASE WHEN (SELECT val FROM PYFYoutlook_cfx) != 0 THEN ((SELECT val FROM FYoutlook_cfx) - (SELECT val FROM PYFYoutlook_cfx)) / ABS((SELECT val FROM PYFYoutlook_cfx)) * 100 ELSE NULL END AS VARIANCE_PYFY_OUTLOOK_CFX_FPNA,
  CASE WHEN (SELECT val FROM PYPQTDactuals_rfx) != 0 THEN ((SELECT val FROM PQTDactuals_rfx) - (SELECT val FROM PYPQTDactuals_rfx)) / ABS((SELECT val FROM PYPQTDactuals_rfx)) * 100 ELSE NULL END AS PYPQTD_ACTUALS_RFX_FPNA,
  CASE WHEN (SELECT val FROM PYPQTDactuals_cfx) != 0 THEN ((SELECT val FROM PQTDactuals_cfx) - (SELECT val FROM PYPQTDactuals_cfx)) / ABS((SELECT val FROM PYPQTDactuals_cfx)) * 100 ELSE NULL END AS PYPQTD_ACTUALS_CFX_FPNA,
  CASE WHEN (SELECT val FROM PYYTDactuals_rfx) != 0 THEN ((SELECT val FROM YTDactuals_rfx) - (SELECT val FROM PYYTDactuals_rfx)) / ABS((SELECT val FROM PYYTDactuals_rfx)) * 100 ELSE NULL END AS PY_YTD_ACTUALS_RFX_FPNA,
  CASE WHEN (SELECT val FROM PYYTDactuals_cfx) != 0 THEN ((SELECT val FROM YTDactuals_cfx) - (SELECT val FROM PYYTDactuals_cfx)) / ABS((SELECT val FROM PYYTDactuals_cfx)) * 100 ELSE NULL END AS PY_YTD_ACTUALS_CFX_FPNA
FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
WHERE alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income''
  AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  AND (
    (alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0)
    OR (alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0)
    OR (alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1)
    OR (alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND (dateconfig.ADD19 = ''CY'' OR dateconfig.ADD19 = ''PY''))
    OR (alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''MTD'')
    OR (alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD'')
  )'
WHERE "ID" = 1;

-- ── UPDATE ID=2: Impairments ───────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH
IMPAIRMENTS_CART AS (
    SELECT A.DATA_TYPE, A.T_VERSION, A.MONTH_ABR, A.CFX, A.RFX, D.ADD16, D.ADD17, D.ADD18
    FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" A
    CROSS JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" D
    WHERE A.M_ACCOUNT_0 = ''Impairments'' AND A.T_REPORTING = ''CIB''
    AND D.FILTER_DATE = ''CURRENT_MONTH'' AND D.FILTER_TYPE = ''PYR+CYR''
),
IMPAIRMENTS_DATE AS (
    SELECT A.DATA_TYPE, A.T_VERSION, A.MONTH_ABR, A.CFX, A.RFX, D.ADD6, D.ADD16, D.ADD18
    FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" A
    JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" D ON A.E_PERIOD_DATE = D.E_PERIOD_DATE
    WHERE A.M_ACCOUNT_0 = ''Impairments'' AND A.T_REPORTING = ''CIB''
    AND D.FILTER_DATE = ''CURRENT_MONTH'' AND D.FILTER_TYPE = ''PYR+CYR''
),
YTD_ACTUALS AS (
    SELECT SUM(CFX) AS YTD_ACTUALS_CFX, SUM(RFX) AS YTD_ACTUALS_RFX
    FROM IMPAIRMENTS_CART WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD16 = 0
),
VS_BUDGET AS (
    SELECT
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND ADD16 = 0 THEN CFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX ELSE 0 END)) * 100 END AS VS_BUDGET_CFX_PCT,
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND ADD16 = 0 THEN RFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX ELSE 0 END)) * 100 END AS VS_BUDGET_RFX_PCT
    FROM IMPAIRMENTS_CART WHERE DATA_TYPE IN (''Actuals'',''Budget'') AND T_VERSION = ''YTD'' AND ADD16 = 0
),
CY_PQ_ACTUALS AS (
    SELECT SUM(CFX) AS CY_PQ_ACTUALS_CFX, SUM(RFX) AS CY_PQ_ACTUALS_RFX
    FROM IMPAIRMENTS_CART WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''QTD'' AND ADD17 = -1
),
FY_OUTLOOK AS (
    SELECT SUM(CFX) AS FY_OUTLOOK_CFX, SUM(RFX) AS FY_OUTLOOK_RFX
    FROM IMPAIRMENTS_CART WHERE DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''Nov'' AND ADD18 = -1
),
PY_PQ_ACTUALS AS (
    SELECT
        CASE WHEN SUM(CASE WHEN ADD17 = -4 THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN ADD17 = -1 THEN CFX ELSE 0 END) - SUM(CASE WHEN ADD17 = -4 THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN ADD17 = -4 THEN CFX ELSE 0 END)) * 100 END AS PY_PQ_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN ADD17 = -4 THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN ADD17 = -1 THEN RFX ELSE 0 END) - SUM(CASE WHEN ADD17 = -4 THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN ADD17 = -4 THEN RFX ELSE 0 END)) * 100 END AS PY_PQ_RFX_VARIANCE
    FROM IMPAIRMENTS_CART WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''QTD'' AND ADD17 IN (-1, -4)
),
YTD_ACTUAL_PY AS (
    SELECT
        CASE WHEN SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN T_VERSION = ''YTD'' AND ADD16 = 0 THEN CFX ELSE 0 END) - SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END)) * 100 END AS YTD_ACTUAL_PY_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN T_VERSION = ''YTD'' AND ADD16 = 0 THEN RFX ELSE 0 END) - SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END)) * 100 END AS YTD_ACTUAL_PY_RFX_VARIANCE
    FROM IMPAIRMENTS_DATE WHERE DATA_TYPE = ''Actuals''
),
FY_OUTLOOK_PY AS (
    SELECT
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''Nov'' AND ADD18 = -1 THEN CFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END)) * 100 END AS FY_OUTLOOK_PY_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''Nov'' AND ADD18 = -1 THEN RFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END)) * 100 END AS FY_OUTLOOK_PY_RFX_VARIANCE
    FROM IMPAIRMENTS_DATE WHERE DATA_TYPE IN (''Outlook_PM'',''Actuals'')
)
SELECT A.YTD_ACTUALS_CFX, A.YTD_ACTUALS_RFX,
       B.VS_BUDGET_CFX_PCT, B.VS_BUDGET_RFX_PCT,
       C.CY_PQ_ACTUALS_CFX, C.CY_PQ_ACTUALS_RFX,
       D.FY_OUTLOOK_CFX, D.FY_OUTLOOK_RFX,
       E.PY_PQ_CFX_VARIANCE, E.PY_PQ_RFX_VARIANCE,
       F.YTD_ACTUAL_PY_CFX_VARIANCE, F.YTD_ACTUAL_PY_RFX_VARIANCE,
       G.FY_OUTLOOK_PY_CFX_VARIANCE, G.FY_OUTLOOK_PY_RFX_VARIANCE
FROM YTD_ACTUALS A CROSS JOIN VS_BUDGET B CROSS JOIN CY_PQ_ACTUALS C
CROSS JOIN FY_OUTLOOK D CROSS JOIN PY_PQ_ACTUALS E
CROSS JOIN YTD_ACTUAL_PY F CROSS JOIN FY_OUTLOOK_PY G'
WHERE "ID" = 2;

-- ── UPDATE ID=3: Underlying Profit ─────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH
UNDERLYING_PROFIT_BASE AS (
    SELECT A.DATA_TYPE, A.T_VERSION, A.MONTH_ABR, A.CFX, A.RFX, D.ADD6, D.ADD16, D.ADD17, D.ADD18
    FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" A
    JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" D ON A.E_PERIOD_DATE = D.E_PERIOD_DATE
    WHERE A.M_ACCOUNT_0 = ''Operating Profit'' AND A.T_REPORTING = ''CIB''
    AND D.FILTER_DATE = ''CURRENT_MONTH'' AND D.FILTER_TYPE = ''PYR+CYR''
),
YTD_ACTUALS AS (
    SELECT SUM(CFX) AS YTD_ACTUALS_CFX, SUM(RFX) AS YTD_ACTUALS_RFX
    FROM UNDERLYING_PROFIT_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD16 = 0
),
VS_BUDGET AS (
    SELECT
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND ADD16 = 0 THEN CFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX ELSE 0 END)) * 100 END AS VS_BUDGET_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND ADD16 = 0 THEN RFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX ELSE 0 END)) * 100 END AS VS_BUDGET_RFX_VARIANCE
    FROM UNDERLYING_PROFIT_BASE WHERE DATA_TYPE IN (''Actuals'',''Budget'') AND T_VERSION = ''YTD''
),
CY_PQ_ACTUALS AS (
    SELECT SUM(CFX) AS CY_PQ_ACTUALS_CFX, SUM(RFX) AS CY_PQ_ACTUALS_RFX
    FROM UNDERLYING_PROFIT_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''QTD'' AND ADD17 = -1
),
FY_OUTLOOK AS (
    SELECT SUM(CFX) AS FY_OUTLOOK_CFX, SUM(RFX) AS FY_OUTLOOK_RFX
    FROM UNDERLYING_PROFIT_BASE WHERE DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD18 = -1
),
PY_PQ_ACTUALS AS (
    SELECT
        CASE WHEN SUM(CASE WHEN ADD17 = -4 THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN ADD17 = -1 THEN CFX ELSE 0 END) - SUM(CASE WHEN ADD17 = -4 THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN ADD17 = -4 THEN CFX ELSE 0 END)) * 100 END AS PY_PQ_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN ADD17 = -4 THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN ADD17 = -1 THEN RFX ELSE 0 END) - SUM(CASE WHEN ADD17 = -4 THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN ADD17 = -4 THEN RFX ELSE 0 END)) * 100 END AS PY_PQ_RFX_VARIANCE
    FROM UNDERLYING_PROFIT_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''QTD'' AND ADD17 IN (-1,-4)
),
YTD_ACTUAL_PY AS (
    SELECT
        CASE WHEN SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN T_VERSION = ''YTD'' AND ADD16 = 0 THEN CFX ELSE 0 END) - SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END)) * 100 END AS YTD_ACTUAL_PY_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN T_VERSION = ''YTD'' AND ADD16 = 0 THEN RFX ELSE 0 END) - SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END)) * 100 END AS YTD_ACTUAL_PY_RFX_VARIANCE
    FROM UNDERLYING_PROFIT_BASE WHERE DATA_TYPE = ''Actuals''
),
FY_OUTLOOK_PY AS (
    SELECT
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD18 = -1 THEN CFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END)) * 100 END AS FY_OUTLOOK_PY_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD18 = -1 THEN RFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END)) * 100 END AS FY_OUTLOOK_PY_RFX_VARIANCE
    FROM UNDERLYING_PROFIT_BASE WHERE DATA_TYPE IN (''Outlook_PM'',''Actuals'')
)
SELECT A.YTD_ACTUALS_CFX, A.YTD_ACTUALS_RFX,
       B.VS_BUDGET_CFX_VARIANCE, B.VS_BUDGET_RFX_VARIANCE,
       C.CY_PQ_ACTUALS_CFX, C.CY_PQ_ACTUALS_RFX,
       D.FY_OUTLOOK_CFX, D.FY_OUTLOOK_RFX,
       E.PY_PQ_CFX_VARIANCE, E.PY_PQ_RFX_VARIANCE,
       F.YTD_ACTUAL_PY_CFX_VARIANCE, F.YTD_ACTUAL_PY_RFX_VARIANCE,
       G.FY_OUTLOOK_PY_CFX_VARIANCE, G.FY_OUTLOOK_PY_RFX_VARIANCE
FROM YTD_ACTUALS A CROSS JOIN VS_BUDGET B CROSS JOIN CY_PQ_ACTUALS C
CROSS JOIN FY_OUTLOOK D CROSS JOIN PY_PQ_ACTUALS E
CROSS JOIN YTD_ACTUAL_PY F CROSS JOIN FY_OUTLOOK_PY G'
WHERE "ID" = 3;

-- ── UPDATE ID=4: Funded Assets ─────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH
FUNDED_ASSETS_BASE AS (
    SELECT A.DATA_TYPE, A.T_VERSION, A.MONTH_ABR, A.CFX, A.RFX, D.ADD6, D.ADD16, D.ADD17, D.ADD18
    FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" A
    JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" D ON A.E_PERIOD_DATE = D.E_PERIOD_DATE
    WHERE A.M_ACCOUNT_1 = ''Funded Assets'' AND A.T_REPORTING = ''CIB''
    AND D.FILTER_DATE = ''CURRENT_MONTH'' AND D.FILTER_TYPE = ''PYR+CYR''
),
YTD_ACTUALS AS (
    SELECT SUM(CFX) AS YTD_ACTUALS_CFX, SUM(RFX) AS YTD_ACTUALS_RFX
    FROM FUNDED_ASSETS_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD16 = 0
),
VS_BUDGET AS (
    SELECT
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND ADD16 = 0 THEN CFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX ELSE 0 END)) * 100 END AS VS_BUDGET_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND ADD16 = 0 THEN RFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX ELSE 0 END)) * 100 END AS VS_BUDGET_RFX_VARIANCE
    FROM FUNDED_ASSETS_BASE WHERE DATA_TYPE IN (''Actuals'',''Budget'') AND T_VERSION = ''YTD''
),
CY_PQ_ACTUALS AS (
    SELECT SUM(CFX) AS CY_PQ_ACTUALS_CFX, SUM(RFX) AS CY_PQ_ACTUALS_RFX
    FROM FUNDED_ASSETS_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''QTD'' AND ADD17 = -1
),
FY_OUTLOOK AS (
    SELECT SUM(CFX) AS FY_OUTLOOK_CFX, SUM(RFX) AS FY_OUTLOOK_RFX
    FROM FUNDED_ASSETS_BASE WHERE DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''Nov'' AND ADD18 = -1
),
PY_PQ_ACTUALS AS (
    SELECT
        CASE WHEN SUM(CASE WHEN ADD17 = -4 THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN ADD17 = -1 THEN CFX ELSE 0 END) - SUM(CASE WHEN ADD17 = -4 THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN ADD17 = -4 THEN CFX ELSE 0 END)) * 100 END AS PY_PQ_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN ADD17 = -4 THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN ADD17 = -1 THEN RFX ELSE 0 END) - SUM(CASE WHEN ADD17 = -4 THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN ADD17 = -4 THEN RFX ELSE 0 END)) * 100 END AS PY_PQ_RFX_VARIANCE
    FROM FUNDED_ASSETS_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''QTD'' AND ADD17 IN (-1,-4)
),
YTD_ACTUAL_PY AS (
    SELECT
        CASE WHEN SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN T_VERSION = ''YTD'' AND ADD16 = 0 THEN CFX ELSE 0 END) - SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END)) * 100 END AS YTD_ACTUAL_PY_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN T_VERSION = ''YTD'' AND ADD16 = 0 THEN RFX ELSE 0 END) - SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END)) * 100 END AS YTD_ACTUAL_PY_RFX_VARIANCE
    FROM FUNDED_ASSETS_BASE WHERE DATA_TYPE = ''Actuals''
),
FY_OUTLOOK_PY AS (
    SELECT
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''Nov'' AND ADD18 = -1 THEN CFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN CFX ELSE 0 END)) * 100 END AS FY_OUTLOOK_PY_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''Nov'' AND ADD18 = -1 THEN RFX ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''MTD'' AND ADD6 = ''PY_YTD'' THEN RFX ELSE 0 END)) * 100 END AS FY_OUTLOOK_PY_RFX_VARIANCE
    FROM FUNDED_ASSETS_BASE WHERE DATA_TYPE IN (''Outlook_PM'',''Actuals'')
)
SELECT A.YTD_ACTUALS_CFX, A.YTD_ACTUALS_RFX,
       B.VS_BUDGET_CFX_VARIANCE, B.VS_BUDGET_RFX_VARIANCE,
       C.CY_PQ_ACTUALS_CFX, C.CY_PQ_ACTUALS_RFX,
       D.FY_OUTLOOK_CFX, D.FY_OUTLOOK_RFX,
       E.PY_PQ_CFX_VARIANCE, E.PY_PQ_RFX_VARIANCE,
       F.YTD_ACTUAL_PY_CFX_VARIANCE, F.YTD_ACTUAL_PY_RFX_VARIANCE,
       G.FY_OUTLOOK_PY_CFX_VARIANCE, G.FY_OUTLOOK_PY_RFX_VARIANCE
FROM YTD_ACTUALS A CROSS JOIN VS_BUDGET B CROSS JOIN CY_PQ_ACTUALS C
CROSS JOIN FY_OUTLOOK D CROSS JOIN PY_PQ_ACTUALS E
CROSS JOIN YTD_ACTUAL_PY F CROSS JOIN FY_OUTLOOK_PY G'
WHERE "ID" = 4;

-- ── UPDATE ID=5: RoTE ──────────────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH
ROTE_BASE AS (
    SELECT A.DATA_TYPE, A.T_VERSION, A.MONTH_ABR, A.CFX_N, A.RFX_N, D.ADD9, D.ADD16, D.ADD17, D.ADD18, D.ADD19
    FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLRATIOS" A
    JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" D ON A.E_PERIOD_DATE = D.E_PERIOD_DATE
    WHERE A.M_ACCOUNT_5 = ''RoTE %'' AND A.T_REPORTING = ''CIB''
    AND D.FILTER_DATE = ''CURRENT_MONTH'' AND D.FILTER_TYPE = ''PYR+CYR''
),
YTD_ACTUALS AS (
    SELECT SUM(CFX_N) AS YTD_ACTUALS_CFX, SUM(RFX_N) AS YTD_ACTUALS_RFX
    FROM ROTE_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD16 = 0
),
VS_BUDGET AS (
    SELECT
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX_N ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND ADD16 = 0 THEN CFX_N ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX_N ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN CFX_N ELSE 0 END)) * 100 END AS VS_BUDGET_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX_N ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND ADD16 = 0 THEN RFX_N ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX_N ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Budget'' AND ADD16 = 0 THEN RFX_N ELSE 0 END)) * 100 END AS VS_BUDGET_RFX_VARIANCE
    FROM ROTE_BASE WHERE DATA_TYPE IN (''Actuals'',''Budget'') AND T_VERSION = ''YTD''
),
PQTR_ACTUALS AS (
    SELECT SUM(CFX_N) AS PQTR_ACTUALS_CFX, SUM(RFX_N) AS PQTR_ACTUALS_RFX
    FROM ROTE_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''QTD'' AND ADD17 = -1
),
FY_OUTLOOK AS (
    SELECT SUM(CFX_N) AS FY_OUTLOOK_CFX, SUM(RFX_N) AS FY_OUTLOOK_RFX
    FROM ROTE_BASE WHERE DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD18 = -1
),
FY_ACTPY AS (
    SELECT
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD19 = ''PY'' THEN CFX_N ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD18 = -1 THEN CFX_N ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD19 = ''PY'' THEN CFX_N ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD19 = ''PY'' THEN CFX_N ELSE 0 END)) * 100 END AS FY_ACTPY_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD19 = ''PY'' THEN RFX_N ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD18 = -1 THEN RFX_N ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD19 = ''PY'' THEN RFX_N ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY'' AND ADD19 = ''PY'' THEN RFX_N ELSE 0 END)) * 100 END AS FY_ACTPY_RFX_VARIANCE
    FROM ROTE_BASE WHERE DATA_TYPE IN (''Outlook_PM'',''Actuals'') AND T_VERSION = ''YTD''
),
PY_PQTR AS (
    SELECT
        CASE WHEN SUM(CASE WHEN ADD17 = -4 THEN CFX_N ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN ADD17 = -1 THEN CFX_N ELSE 0 END) - SUM(CASE WHEN ADD17 = -4 THEN CFX_N ELSE 0 END))
             / ABS(SUM(CASE WHEN ADD17 = -4 THEN CFX_N ELSE 0 END)) * 100 END AS PY_PQTR_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN ADD17 = -4 THEN RFX_N ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN ADD17 = -1 THEN RFX_N ELSE 0 END) - SUM(CASE WHEN ADD17 = -4 THEN RFX_N ELSE 0 END))
             / ABS(SUM(CASE WHEN ADD17 = -4 THEN RFX_N ELSE 0 END)) * 100 END AS PY_PQTR_RFX_VARIANCE
    FROM ROTE_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''QTD'' AND ADD17 IN (-1,-4)
),
PYYTD_ACTUALS AS (
    SELECT
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD9 = ''2025_M01'' THEN CFX_N ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD16 = 0 THEN CFX_N ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD9 = ''2025_M01'' THEN CFX_N ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD9 = ''2025_M01'' THEN CFX_N ELSE 0 END)) * 100 END AS PYYTD_CFX_VARIANCE,
        CASE WHEN SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD9 = ''2025_M01'' THEN RFX_N ELSE 0 END) = 0 THEN NULL
        ELSE (SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD16 = 0 THEN RFX_N ELSE 0 END) - SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD9 = ''2025_M01'' THEN RFX_N ELSE 0 END))
             / ABS(SUM(CASE WHEN DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND ADD9 = ''2025_M01'' THEN RFX_N ELSE 0 END)) * 100 END AS PYYTD_RFX_VARIANCE
    FROM ROTE_BASE WHERE DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD''
)
SELECT A.YTD_ACTUALS_CFX, A.YTD_ACTUALS_RFX,
       B.VS_BUDGET_CFX_VARIANCE, B.VS_BUDGET_RFX_VARIANCE,
       C.PQTR_ACTUALS_CFX, C.PQTR_ACTUALS_RFX,
       D.FY_OUTLOOK_CFX, D.FY_OUTLOOK_RFX,
       E.FY_ACTPY_CFX_VARIANCE, E.FY_ACTPY_RFX_VARIANCE,
       F.PY_PQTR_CFX_VARIANCE, F.PY_PQTR_RFX_VARIANCE,
       G.PYYTD_CFX_VARIANCE, G.PYYTD_RFX_VARIANCE
FROM YTD_ACTUALS A CROSS JOIN VS_BUDGET B CROSS JOIN PQTR_ACTUALS C
CROSS JOIN FY_OUTLOOK D CROSS JOIN FY_ACTPY E CROSS JOIN PY_PQTR F CROSS JOIN PYYTD_ACTUALS G'
WHERE "ID" = 5;

-- ── UPDATE ID=6: Costs ─────────────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH
  CYPQactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -1 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  PYPQactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  CYPQactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -1 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  PYPQactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD16 = 0 AND alldata.T_VERSION = ''YTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactualPY_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD16 = 0 AND alldata.T_VERSION = ''YTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactualPY_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  FYoutlook_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''CY'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  FYoutlook_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''CY'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR'')
SELECT
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) AS YTD_ACTUALS_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) AS YTD_ACTUALS_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) - SUM(CASE WHEN alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) AS VS_BUDGET_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) - SUM(CASE WHEN alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) AS VS_BUDGET_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1 THEN alldata.RFX ELSE 0 END) AS PQTD_ACTUALS_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1 THEN alldata.CFX ELSE 0 END) AS PQTD_ACTUALS_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'' THEN alldata.RFX ELSE 0 END) AS FY_OUTLOOK_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'' THEN alldata.CFX ELSE 0 END) AS FY_OUTLOOK_CFX_FPNA,
  CASE WHEN (SELECT val FROM PYPQactuals_rfx) != 0 THEN ((SELECT val FROM CYPQactuals_rfx) - (SELECT val FROM PYPQactuals_rfx)) / ABS((SELECT val FROM PYPQactuals_rfx)) * 100 ELSE NULL END AS VARIANCE_PYPQ_Actuals_RFX_FPNA,
  CASE WHEN (SELECT val FROM PYPQactuals_cfx) != 0 THEN ((SELECT val FROM CYPQactuals_cfx) - (SELECT val FROM PYPQactuals_cfx)) / ABS((SELECT val FROM PYPQactuals_cfx)) * 100 ELSE NULL END AS VARIANCE_PYPQ_Actuals_CFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_rfx) != 0 THEN ((SELECT val FROM YTDactuals_rfx) - (SELECT val FROM YTDactualPY_rfx)) / ABS((SELECT val FROM YTDactualPY_rfx)) * 100 ELSE NULL END AS YTD_ACTUAL_RFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_cfx) != 0 THEN ((SELECT val FROM YTDactuals_cfx) - (SELECT val FROM YTDactualPY_cfx)) / ABS((SELECT val FROM YTDactualPY_cfx)) * 100 ELSE NULL END AS YTD_ACTUAL_CFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_rfx) != 0 THEN ((SELECT val FROM FYoutlook_rfx) - (SELECT val FROM YTDactualPY_rfx)) / ABS((SELECT val FROM YTDactualPY_rfx)) * 100 ELSE NULL END AS YTD_ACTUAL_2_RFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_cfx) != 0 THEN ((SELECT val FROM FYoutlook_cfx) - (SELECT val FROM YTDactualPY_cfx)) / ABS((SELECT val FROM YTDactualPY_cfx)) * 100 ELSE NULL END AS YTD_ACTUAL_2_CFX_FPNA
FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
WHERE alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Total Cost''
  AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  AND ((alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0)
    OR (alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0)
    OR (alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1)
    OR (alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'')
    OR (alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''QTD'')
    OR (alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD''))'
WHERE "ID" = 6;

-- ── UPDATE ID=7: NII ───────────────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH
  YTDactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD16 = 0 AND alldata.T_VERSION = ''YTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactualPY_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD16 = 0 AND alldata.T_VERSION = ''YTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactualPY_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  CYPQactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -1 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  PYPQactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  CYPQactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -1 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  PYPQactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  FYoutlook_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''CY'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  PYYTDactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  FYoutlook_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''CY'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  PYYTDactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR'')
SELECT
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) AS YTD_ACTUALS_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) AS YTD_ACTUALS_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) - SUM(CASE WHEN alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) AS VS_BUDGET_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) - SUM(CASE WHEN alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) AS VS_BUDGET_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1 THEN alldata.RFX ELSE 0 END) AS PQTD_ACTUALS_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1 THEN alldata.CFX ELSE 0 END) AS PQTD_ACTUALS_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'' THEN alldata.RFX ELSE 0 END) AS FY_OUTLOOK_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'' THEN alldata.CFX ELSE 0 END) AS FY_OUTLOOK_CFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_rfx) != 0 THEN ((SELECT val FROM YTDactuals_rfx) - (SELECT val FROM YTDactualPY_rfx)) / ABS((SELECT val FROM YTDactualPY_rfx)) * 100 ELSE NULL END AS VARIANCE_YTD_Actual_RFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_cfx) != 0 THEN ((SELECT val FROM YTDactuals_cfx) - (SELECT val FROM YTDactualPY_cfx)) / ABS((SELECT val FROM YTDactualPY_cfx)) * 100 ELSE NULL END AS VARIANCE_YTD_Actual_CFX_FPNA,
  CASE WHEN (SELECT val FROM PYPQactuals_rfx) != 0 THEN ((SELECT val FROM CYPQactuals_rfx) - (SELECT val FROM PYPQactuals_rfx)) / ABS((SELECT val FROM PYPQactuals_rfx)) * 100 ELSE NULL END AS PYPQ_ACTUALS_RFX_FPNA,
  CASE WHEN (SELECT val FROM PYPQactuals_cfx) != 0 THEN ((SELECT val FROM CYPQactuals_cfx) - (SELECT val FROM PYPQactuals_cfx)) / ABS((SELECT val FROM PYPQactuals_cfx)) * 100 ELSE NULL END AS PYPQ_ACTUALS_CFX_FPNA,
  CASE WHEN (SELECT val FROM PYYTDactuals_rfx) != 0 THEN ((SELECT val FROM FYoutlook_rfx) - (SELECT val FROM PYYTDactuals_rfx)) / ABS((SELECT val FROM PYYTDactuals_rfx)) * 100 ELSE NULL END AS PY_YTD_ACTUALS_RFX_FPNA,
  CASE WHEN (SELECT val FROM PYYTDactuals_cfx) != 0 THEN ((SELECT val FROM FYoutlook_cfx) - (SELECT val FROM PYYTDactuals_cfx)) / ABS((SELECT val FROM PYYTDactuals_cfx)) * 100 ELSE NULL END AS PY_YTD_ACTUALS_CFX_FPNA
FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
WHERE alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_0 = ''Income'' AND alldata.M_ACCOUNT_1 = ''Net Interest Income''
  AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  AND ((alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0)
    OR (alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0)
    OR (alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1)
    OR (alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'')
    OR (alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''QTD'')
    OR (alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD''))'
WHERE "ID" = 7;

-- ── UPDATE ID=8: First RWA ─────────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH
  CYPQactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -1 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  PYPQactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  CYPQactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -1 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  PYPQactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''QTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactuals_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD16 = 0 AND alldata.T_VERSION = ''YTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactualPY_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactuals_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD16 = 0 AND alldata.T_VERSION = ''YTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  YTDactualPY_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  FYoutlook_rfx AS (SELECT SUM(alldata.RFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''CY'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''),
  FYoutlook_cfx AS (SELECT SUM(alldata.CFX) AS val FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE WHERE alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND alldata.MONTH_ABR = ''FY'' AND dateconfig.ADD19 = ''CY'' AND alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities'' AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR'')
SELECT
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) AS YTD_ACTUALS_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) AS YTD_ACTUALS_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) - SUM(CASE WHEN alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.RFX ELSE 0 END) AS VS_BUDGET_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) - SUM(CASE WHEN alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0 THEN alldata.CFX ELSE 0 END) AS VS_BUDGET_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1 THEN alldata.RFX ELSE 0 END) AS PQTD_ACTUALS_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1 THEN alldata.CFX ELSE 0 END) AS PQTD_ACTUALS_CFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'' THEN alldata.RFX ELSE 0 END) AS FY_OUTLOOK_RFX_FPNA,
  SUM(CASE WHEN alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'' THEN alldata.CFX ELSE 0 END) AS FY_OUTLOOK_CFX_FPNA,
  CASE WHEN (SELECT val FROM PYPQactuals_rfx) != 0 THEN ((SELECT val FROM CYPQactuals_rfx) - (SELECT val FROM PYPQactuals_rfx)) / ABS((SELECT val FROM PYPQactuals_rfx)) * 100 ELSE NULL END AS VARIANCE_PYPQ_Actuals_RFX_FPNA,
  CASE WHEN (SELECT val FROM PYPQactuals_cfx) != 0 THEN ((SELECT val FROM CYPQactuals_cfx) - (SELECT val FROM PYPQactuals_cfx)) / ABS((SELECT val FROM PYPQactuals_cfx)) * 100 ELSE NULL END AS VARIANCE_PYPQ_Actuals_CFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_rfx) != 0 THEN ((SELECT val FROM YTDactuals_rfx) - (SELECT val FROM YTDactualPY_rfx)) / ABS((SELECT val FROM YTDactualPY_rfx)) * 100 ELSE NULL END AS YTD_ACTUAL_RFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_cfx) != 0 THEN ((SELECT val FROM YTDactuals_cfx) - (SELECT val FROM YTDactualPY_cfx)) / ABS((SELECT val FROM YTDactualPY_cfx)) * 100 ELSE NULL END AS YTD_ACTUAL_CFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_rfx) != 0 THEN ((SELECT val FROM FYoutlook_rfx) - (SELECT val FROM YTDactualPY_rfx)) / ABS((SELECT val FROM YTDactualPY_rfx)) * 100 ELSE NULL END AS YTD_ACTUAL_2_RFX_FPNA,
  CASE WHEN (SELECT val FROM YTDactualPY_cfx) != 0 THEN ((SELECT val FROM FYoutlook_cfx) - (SELECT val FROM YTDactualPY_cfx)) / ABS((SELECT val FROM YTDactualPY_cfx)) * 100 ELSE NULL END AS YTD_ACTUAL_2_CFX_FPNA
FROM "T1NFRP_PHY"."CV_UP_NFRP_ALLDATA" alldata
INNER JOIN "T1NFRP_PHY"."TBL_NFRP_DATE_CONFIG" dateconfig ON alldata.E_PERIOD_DATE = dateconfig.E_PERIOD_DATE
WHERE alldata.T_REPORTING = ''FPNA'' AND alldata.M_ACCOUNT_1 = ''Funded Liabilities''
  AND dateconfig.FILTER_DATE = ''CURRENT_MONTH'' AND dateconfig.FILTER_TYPE = ''PYR+CYR''
  AND ((alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0)
    OR (alldata.DATA_TYPE = ''Budget'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD16 = 0)
    OR (alldata.DATA_TYPE = ''Actuals'' AND alldata.T_VERSION = ''QTD'' AND dateconfig.ADD17 = -1)
    OR (alldata.DATA_TYPE = ''Outlook_PM'' AND alldata.T_VERSION = ''YTD'' AND dateconfig.ADD19 = ''CY'' AND alldata.MONTH_ABR = ''FY'')
    OR (alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD17 = -5 AND alldata.T_VERSION = ''QTD'')
    OR (alldata.DATA_TYPE = ''Actuals'' AND dateconfig.ADD6 = ''PY_YTD'' AND alldata.T_VERSION = ''MTD''))'
WHERE "ID" = 8;

-- ── UPDATE ID=9: JAWS ──────────────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH DATA_ANCHOR AS (
    SELECT MAX(A.E_PERIOD_DATE) AS ACTUALS_YTD_DATE
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA" A
    WHERE A.M_ACCOUNT_5 = ''Software''
    AND   A.T_REPORTING = ''FPNA''
    AND   A.DATA_TYPE   = ''Actuals''
    AND   A.T_VERSION   = ''YTD''
    AND   A.CFX        != 0
    AND EXISTS (
        SELECT 1 FROM T1NFRP_PHY."TBL_NFRP_DATE_CONFIG" D
        WHERE D.FILTER_DATE = TO_VARCHAR(A.E_PERIOD_DATE, ''YYYY-MM-DD'')
    )
),
PERIODS AS (
    SELECT
        MAX(CASE WHEN D.ADD16 = ''0''                         THEN D.E_PERIOD_DATE END) AS CURRENT_YTD_PERIOD,
        MAX(CASE WHEN D.ADD16 = ''-12''                       THEN D.E_PERIOD_DATE END) AS PYYTD_PERIOD,
        MAX(CASE WHEN D.ADD17 = ''-1'' AND D.ADD19 = ''CY''   THEN D.E_PERIOD_DATE END) AS PREV_QTR_PERIOD,
        MAX(CASE WHEN D.ADD17 = ''-5'' AND D.ADD19 = ''PY''   THEN D.E_PERIOD_DATE END) AS PYPQTR_PERIOD
    FROM T1NFRP_PHY."TBL_NFRP_DATE_CONFIG" D
    CROSS JOIN DATA_ANCHOR A
    WHERE D.FILTER_DATE = TO_VARCHAR(A.ACTUALS_YTD_DATE, ''YYYY-MM-DD'')
),
FY_ANCHOR AS (
    SELECT MAX(E_PERIOD_DATE) AS FY_ACTPY_PERIOD
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA"
    WHERE M_ACCOUNT_5 = ''Software'' AND T_REPORTING = ''FPNA''
    AND   DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY''
),
FY_OUTLOOK_ANCHOR AS (
    SELECT MAX(E_PERIOD_DATE) AS FY_OUTLOOK_PERIOD
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA"
    WHERE M_ACCOUNT_5 = ''Software'' AND E_BOOKS = ''NEWF - OL''
    AND   T_REPORTING = ''FPNA'' AND DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD''
),
PERIOD_SET AS (
    SELECT P.CURRENT_YTD_PERIOD, P.PYYTD_PERIOD, P.PREV_QTR_PERIOD, P.PYPQTR_PERIOD,
           FA.FY_ACTPY_PERIOD, OA.FY_OUTLOOK_PERIOD
    FROM PERIODS P CROSS JOIN FY_ANCHOR FA CROSS JOIN FY_OUTLOOK_ANCHOR OA
),
ALL_MEASURES AS (
    SELECT
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.CFX ELSE 0 END) AS YTD_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Budget''    AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.CFX ELSE 0 END) AS RBUDYTD_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.PREV_QTR_PERIOD    THEN A.CFX ELSE 0 END) AS PQTR_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Outlook_PM'' AND A.T_VERSION=''YTD'' AND A.E_BOOKS=''NEWF - OL'' AND A.E_PERIOD_DATE=PS.FY_OUTLOOK_PERIOD THEN A.CFX ELSE 0 END) AS FY_OUTLOOK_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''YTD'' AND A.MONTH_ABR=''FY'' AND A.E_PERIOD_DATE=PS.FY_ACTPY_PERIOD   THEN A.CFX ELSE 0 END) AS FY_ACTPY_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.PYYTD_PERIOD       THEN A.CFX ELSE 0 END) AS PYYTD_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.PYPQTR_PERIOD      THEN A.CFX ELSE 0 END) AS PYPQTR_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.RFX ELSE 0 END) AS YTD_ACTUALS_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Budget''    AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.RFX ELSE 0 END) AS RBUDYTD_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.PREV_QTR_PERIOD    THEN A.RFX ELSE 0 END) AS PQTR_ACTUALS_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Outlook_PM'' AND A.T_VERSION=''YTD'' AND A.E_BOOKS=''NEWF - OL'' AND A.E_PERIOD_DATE=PS.FY_OUTLOOK_PERIOD THEN A.RFX ELSE 0 END) AS FY_OUTLOOK_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''YTD'' AND A.MONTH_ABR=''FY'' AND A.E_PERIOD_DATE=PS.FY_ACTPY_PERIOD   THEN A.RFX ELSE 0 END) AS FY_ACTPY_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.PYYTD_PERIOD       THEN A.RFX ELSE 0 END) AS PYYTD_ACTUALS_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''   AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.PYPQTR_PERIOD      THEN A.RFX ELSE 0 END) AS PYPQTR_ACTUALS_RFX
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA" A CROSS JOIN PERIOD_SET PS
    WHERE A.M_ACCOUNT_5 = ''Software'' AND A.T_REPORTING = ''FPNA''
    AND A.E_PERIOD_DATE IN (PS.CURRENT_YTD_PERIOD,PS.PYYTD_PERIOD,PS.PREV_QTR_PERIOD,PS.PYPQTR_PERIOD,PS.FY_ACTPY_PERIOD,PS.FY_OUTLOOK_PERIOD)
)
SELECT
    M.YTD_ACTUALS_CFX,
    (M.YTD_ACTUALS_CFX  - M.RBUDYTD_CFX)        AS VS_BUDGET_CFX,
    M.PQTR_ACTUALS_CFX,
    M.FY_OUTLOOK_CFX,
    (M.FY_OUTLOOK_CFX   - M.FY_ACTPY_CFX)       AS VAR_FY_ACTPY_CFX,
    (M.PQTR_ACTUALS_CFX - M.PYPQTR_ACTUALS_CFX) AS VAR_PYPQTR_CFX,
    (M.YTD_ACTUALS_CFX  - M.PYYTD_ACTUALS_CFX)  AS VAR_PYYTD_CFX,
    M.YTD_ACTUALS_RFX,
    (M.YTD_ACTUALS_RFX  - M.RBUDYTD_RFX)        AS VS_BUDGET_RFX,
    M.PQTR_ACTUALS_RFX,
    M.FY_OUTLOOK_RFX,
    (M.FY_OUTLOOK_RFX   - M.FY_ACTPY_RFX)       AS VAR_FY_ACTPY_RFX,
    (M.PQTR_ACTUALS_RFX - M.PYPQTR_ACTUALS_RFX) AS VAR_PYPQTR_RFX,
    (M.YTD_ACTUALS_RFX  - M.PYYTD_ACTUALS_RFX)  AS VAR_PYYTD_RFX
FROM PERIOD_SET PS CROSS JOIN ALL_MEASURES M'
WHERE "ID" = 9;

-- ── UPDATE ID=10: CIR ───────────────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH DATA_ANCHOR AS (
    SELECT MAX(R.E_PERIOD_DATE) AS ACTUALS_YTD_DATE
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLRATIOS" R
    WHERE R.M_ACCOUNT_5 LIKE ''CIR %''
    AND   R.T_REPORTING = ''FPNA''
    AND   R.DATA_TYPE   = ''Actuals''
    AND   R.T_VERSION   = ''YTD''
    AND   R.CFX_N      != 0
    AND EXISTS (
        SELECT 1 FROM T1NFRP_PHY."TBL_NFRP_DATE_CONFIG" D
        WHERE D.FILTER_DATE = TO_VARCHAR(R.E_PERIOD_DATE, ''YYYY-MM-DD'')
    )
),
PERIODS AS (
    SELECT
        MAX(CASE WHEN D.ADD16 = ''0''                         THEN D.E_PERIOD_DATE END) AS CURRENT_YTD_PERIOD,
        MAX(CASE WHEN D.ADD16 = ''-12''                       THEN D.E_PERIOD_DATE END) AS PYYTD_PERIOD,
        MAX(CASE WHEN D.ADD17 = ''-1'' AND D.ADD19 = ''CY''   THEN D.E_PERIOD_DATE END) AS PREV_QTR_PERIOD,
        MAX(CASE WHEN D.ADD17 = ''-5'' AND D.ADD19 = ''PY''   THEN D.E_PERIOD_DATE END) AS PYPQTR_PERIOD
    FROM T1NFRP_PHY."TBL_NFRP_DATE_CONFIG" D
    CROSS JOIN DATA_ANCHOR A
    WHERE D.FILTER_DATE = TO_VARCHAR(A.ACTUALS_YTD_DATE, ''YYYY-MM-DD'')
),
FY_ANCHOR AS (
    SELECT MAX(E_PERIOD_DATE) AS FY_ACTPY_PERIOD
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLRATIOS"
    WHERE M_ACCOUNT_5 LIKE ''CIR %'' AND T_REPORTING = ''FPNA''
    AND   DATA_TYPE = ''Actuals'' AND T_VERSION = ''YTD'' AND MONTH_ABR = ''FY''
),
FY_OUTLOOK_ANCHOR AS (
    SELECT MAX(E_PERIOD_DATE) AS FY_OUTLOOK_PERIOD
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLRATIOS"
    WHERE M_ACCOUNT_5 LIKE ''CIR %'' AND E_BOOKS = ''NEWF - OL''
    AND   T_REPORTING = ''FPNA'' AND DATA_TYPE = ''Outlook_PM'' AND T_VERSION = ''YTD''
),
PERIOD_SET AS (
    SELECT P.CURRENT_YTD_PERIOD, P.PYYTD_PERIOD, P.PREV_QTR_PERIOD, P.PYPQTR_PERIOD,
           FA.FY_ACTPY_PERIOD, OA.FY_OUTLOOK_PERIOD
    FROM PERIODS P CROSS JOIN FY_ANCHOR FA CROSS JOIN FY_OUTLOOK_ANCHOR OA
),
ALL_MEASURES AS (
    SELECT
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''YTD'' AND R.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN R.CFX_N ELSE 0 END) AS YTD_ACTUALS_CFX,
        SUM(CASE WHEN R.DATA_TYPE=''Budget''     AND R.T_VERSION=''YTD'' AND R.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN R.CFX_N ELSE 0 END) AS RBUDYTD_CFX,
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''QTD'' AND R.E_PERIOD_DATE=PS.PREV_QTR_PERIOD    THEN R.CFX_N ELSE 0 END) AS PQTR_ACTUALS_CFX,
        SUM(CASE WHEN R.DATA_TYPE=''Outlook_PM'' AND R.T_VERSION=''YTD'' AND R.E_BOOKS=''NEWF - OL'' AND R.E_PERIOD_DATE=PS.FY_OUTLOOK_PERIOD THEN R.CFX_N ELSE 0 END) AS FY_OUTLOOK_CFX,
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''YTD'' AND R.MONTH_ABR=''FY'' AND R.E_PERIOD_DATE=PS.FY_ACTPY_PERIOD   THEN R.CFX_N ELSE 0 END) AS FY_ACTPY_CFX,
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''YTD'' AND R.E_PERIOD_DATE=PS.PYYTD_PERIOD       THEN R.CFX_N ELSE 0 END) AS PYYTD_ACTUALS_CFX,
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''QTD'' AND R.E_PERIOD_DATE=PS.PYPQTR_PERIOD      THEN R.CFX_N ELSE 0 END) AS PYPQTR_ACTUALS_CFX,
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''YTD'' AND R.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN R.RFX_N ELSE 0 END) AS YTD_ACTUALS_RFX,
        SUM(CASE WHEN R.DATA_TYPE=''Budget''     AND R.T_VERSION=''YTD'' AND R.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN R.RFX_N ELSE 0 END) AS RBUDYTD_RFX,
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''QTD'' AND R.E_PERIOD_DATE=PS.PREV_QTR_PERIOD    THEN R.RFX_N ELSE 0 END) AS PQTR_ACTUALS_RFX,
        SUM(CASE WHEN R.DATA_TYPE=''Outlook_PM'' AND R.T_VERSION=''YTD'' AND R.E_BOOKS=''NEWF - OL'' AND R.E_PERIOD_DATE=PS.FY_OUTLOOK_PERIOD THEN R.RFX_N ELSE 0 END) AS FY_OUTLOOK_RFX,
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''YTD'' AND R.MONTH_ABR=''FY'' AND R.E_PERIOD_DATE=PS.FY_ACTPY_PERIOD   THEN R.RFX_N ELSE 0 END) AS FY_ACTPY_RFX,
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''YTD'' AND R.E_PERIOD_DATE=PS.PYYTD_PERIOD       THEN R.RFX_N ELSE 0 END) AS PYYTD_ACTUALS_RFX,
        SUM(CASE WHEN R.DATA_TYPE=''Actuals''    AND R.T_VERSION=''QTD'' AND R.E_PERIOD_DATE=PS.PYPQTR_PERIOD      THEN R.RFX_N ELSE 0 END) AS PYPQTR_ACTUALS_RFX
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLRATIOS" R CROSS JOIN PERIOD_SET PS
    WHERE R.M_ACCOUNT_5 LIKE ''CIR %'' AND R.T_REPORTING = ''FPNA''
    AND R.E_PERIOD_DATE IN (PS.CURRENT_YTD_PERIOD,PS.PYYTD_PERIOD,PS.PREV_QTR_PERIOD,PS.PYPQTR_PERIOD,PS.FY_ACTPY_PERIOD,PS.FY_OUTLOOK_PERIOD)
)
SELECT
    M.YTD_ACTUALS_CFX,
    (M.YTD_ACTUALS_CFX  - M.RBUDYTD_CFX)        AS VS_BUDGET_CFX,
    M.PQTR_ACTUALS_CFX,
    M.FY_OUTLOOK_CFX,
    (M.FY_OUTLOOK_CFX   - M.FY_ACTPY_CFX)       AS VAR_FY_ACTPY_CFX,
    (M.PQTR_ACTUALS_CFX - M.PYPQTR_ACTUALS_CFX) AS VAR_PYPQTR_CFX,
    (M.YTD_ACTUALS_CFX  - M.PYYTD_ACTUALS_CFX)  AS VAR_PYYTD_CFX,
    M.YTD_ACTUALS_RFX,
    (M.YTD_ACTUALS_RFX  - M.RBUDYTD_RFX)        AS VS_BUDGET_RFX,
    M.PQTR_ACTUALS_RFX,
    M.FY_OUTLOOK_RFX,
    (M.FY_OUTLOOK_RFX   - M.FY_ACTPY_RFX)       AS VAR_FY_ACTPY_RFX,
    (M.PQTR_ACTUALS_RFX - M.PYPQTR_ACTUALS_RFX) AS VAR_PYPQTR_RFX,
    (M.YTD_ACTUALS_RFX  - M.PYYTD_ACTUALS_RFX)  AS VAR_PYYTD_RFX
FROM PERIOD_SET PS CROSS JOIN ALL_MEASURES M'
WHERE "ID" = 10;

-- ── UPDATE ID=11: Controllable Headcount ────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH DATA_ANCHOR AS (
    SELECT MAX(A.E_PERIOD_DATE) AS ACTUALS_YTD_DATE
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA" A
    WHERE A.M_ACCOUNT_0 = ''Headcount''
    AND   A.M_ACCOUNT_1 = ''Controllable FTE''
    AND   A.T_REPORTING = ''FPNA''
    AND   A.DATA_TYPE   = ''Actuals''
    AND   A.T_VERSION   = ''YTD''
    AND   A.CFX        != 0
    AND EXISTS (
        SELECT 1 FROM T1NFRP_PHY."TBL_NFRP_DATE_CONFIG" D
        WHERE D.FILTER_DATE = TO_VARCHAR(A.E_PERIOD_DATE, ''YYYY-MM-DD'')
    )
),
PERIODS AS (
    SELECT
        MAX(CASE WHEN D.ADD16 = ''0''                         THEN D.E_PERIOD_DATE END) AS CURRENT_YTD_PERIOD,
        MAX(CASE WHEN D.ADD17 = ''-1'' AND D.ADD19 = ''CY''   THEN D.E_PERIOD_DATE END) AS CY_PQ_PERIOD,
        MAX(CASE WHEN D.ADD17 = ''-5'' AND D.ADD19 = ''PY''   THEN D.E_PERIOD_DATE END) AS PY_PQ_PERIOD,
        MAX(CASE WHEN D.ADD6  = ''PY_YTD''                    THEN D.E_PERIOD_DATE END) AS YTD_PY_PERIOD
    FROM T1NFRP_PHY."TBL_NFRP_DATE_CONFIG" D
    CROSS JOIN DATA_ANCHOR A
    WHERE D.FILTER_DATE = TO_VARCHAR(A.ACTUALS_YTD_DATE, ''YYYY-MM-DD'')
),
FY_OUTLOOK_ANCHOR AS (
    SELECT MAX(E_PERIOD_DATE) AS FY_OUTLOOK_PERIOD
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA"
    WHERE M_ACCOUNT_0 = ''Headcount'' AND M_ACCOUNT_1 = ''Controllable FTE''
    AND   T_REPORTING = ''FPNA'' AND DATA_TYPE = ''Outlook_PM''
    AND   T_VERSION = ''YTD'' AND MONTH_ABR = ''FY''
),
PERIOD_SET AS (
    SELECT P.CURRENT_YTD_PERIOD, P.CY_PQ_PERIOD, P.PY_PQ_PERIOD,
           P.YTD_PY_PERIOD, OA.FY_OUTLOOK_PERIOD
    FROM PERIODS P CROSS JOIN FY_OUTLOOK_ANCHOR OA
),
ALL_MEASURES AS (
    SELECT
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.CFX ELSE 0 END) AS YTD_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Budget''     AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.CFX ELSE 0 END) AS YTDB_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.CY_PQ_PERIOD       THEN A.CFX ELSE 0 END) AS CY_PQ_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Outlook_PM'' AND A.T_VERSION=''YTD'' AND A.MONTH_ABR=''FY'' AND A.E_PERIOD_DATE=PS.FY_OUTLOOK_PERIOD THEN A.CFX ELSE 0 END) AS FY_OUTLOOK_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''MTD'' AND A.E_PERIOD_DATE=PS.YTD_PY_PERIOD      THEN A.CFX ELSE 0 END) AS YTD_ACTUALS_PY_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.PY_PQ_PERIOD       THEN A.CFX ELSE 0 END) AS PY_PQ_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.RFX ELSE 0 END) AS YTD_ACTUALS_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Budget''     AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.RFX ELSE 0 END) AS YTDB_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.CY_PQ_PERIOD       THEN A.RFX ELSE 0 END) AS CY_PQ_ACTUALS_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Outlook_PM'' AND A.T_VERSION=''YTD'' AND A.MONTH_ABR=''FY'' AND A.E_PERIOD_DATE=PS.FY_OUTLOOK_PERIOD THEN A.RFX ELSE 0 END) AS FY_OUTLOOK_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''MTD'' AND A.E_PERIOD_DATE=PS.YTD_PY_PERIOD      THEN A.RFX ELSE 0 END) AS YTD_ACTUALS_PY_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.PY_PQ_PERIOD       THEN A.RFX ELSE 0 END) AS PY_PQ_ACTUALS_RFX
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA" A CROSS JOIN PERIOD_SET PS
    WHERE A.M_ACCOUNT_0 = ''Headcount'' AND A.M_ACCOUNT_1 = ''Controllable FTE''
    AND   A.T_REPORTING = ''FPNA''
    AND   A.E_PERIOD_DATE IN (PS.CURRENT_YTD_PERIOD,PS.CY_PQ_PERIOD,PS.PY_PQ_PERIOD,PS.YTD_PY_PERIOD,PS.FY_OUTLOOK_PERIOD)
)
SELECT
    M.YTD_ACTUALS_CFX,
    (M.YTD_ACTUALS_CFX   - M.YTDB_CFX)           AS VS_BUDGET_CFX,
    M.CY_PQ_ACTUALS_CFX,
    M.FY_OUTLOOK_CFX,
    (M.CY_PQ_ACTUALS_CFX - M.PY_PQ_ACTUALS_CFX)  AS VAR_PY_PQ_YOY_CFX,
    (M.YTD_ACTUALS_CFX   - M.YTD_ACTUALS_PY_CFX) AS VAR_YTD_PY_YOY_CFX,
    (M.FY_OUTLOOK_CFX    - M.YTD_ACTUALS_PY_CFX) AS VAR_FY_VS_PY_CFX,
    M.YTD_ACTUALS_RFX,
    (M.YTD_ACTUALS_RFX   - M.YTDB_RFX)           AS VS_BUDGET_RFX,
    M.CY_PQ_ACTUALS_RFX,
    M.FY_OUTLOOK_RFX,
    (M.CY_PQ_ACTUALS_RFX - M.PY_PQ_ACTUALS_RFX)  AS VAR_PY_PQ_YOY_RFX,
    (M.YTD_ACTUALS_RFX   - M.YTD_ACTUALS_PY_RFX) AS VAR_YTD_PY_YOY_RFX,
    (M.FY_OUTLOOK_RFX    - M.YTD_ACTUALS_PY_RFX) AS VAR_FY_VS_PY_RFX
FROM PERIOD_SET PS CROSS JOIN ALL_MEASURES M'
WHERE "ID" = 11;

-- ── UPDATE ID=12: Second RWA ────────────────────────────────────────

UPDATE "NRFP_FINANCIALS_REPORTINGMASTER"
SET "QUERY" = 'WITH DATA_ANCHOR AS (
    SELECT MAX(A.E_PERIOD_DATE) AS ACTUALS_YTD_DATE
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA" A
    WHERE A.M_ACCOUNT_0 = ''Risk Weighted Assets''
    AND   A.T_REPORTING = ''FPNA''
    AND   A.DATA_TYPE   = ''Actuals''
    AND   A.T_VERSION   = ''YTD''
    AND   A.CFX        != 0
    AND EXISTS (
        SELECT 1 FROM T1NFRP_PHY."TBL_NFRP_DATE_CONFIG" D
        WHERE D.FILTER_DATE = TO_VARCHAR(A.E_PERIOD_DATE, ''YYYY-MM-DD'')
    )
),
PERIODS AS (
    SELECT
        MAX(CASE WHEN D.ADD16 = ''0''                         THEN D.E_PERIOD_DATE END) AS CURRENT_YTD_PERIOD,
        MAX(CASE WHEN D.ADD17 = ''-1'' AND D.ADD19 = ''CY''   THEN D.E_PERIOD_DATE END) AS CY_PQ_PERIOD,
        MAX(CASE WHEN D.ADD17 = ''-5'' AND D.ADD19 = ''PY''   THEN D.E_PERIOD_DATE END) AS PY_PQ_PERIOD,
        MAX(CASE WHEN D.ADD6  = ''PY_YTD''                    THEN D.E_PERIOD_DATE END) AS YTD_PY_PERIOD
    FROM T1NFRP_PHY."TBL_NFRP_DATE_CONFIG" D
    CROSS JOIN DATA_ANCHOR A
    WHERE D.FILTER_DATE = TO_VARCHAR(A.ACTUALS_YTD_DATE, ''YYYY-MM-DD'')
),
FY_OUTLOOK_ANCHOR AS (
    SELECT MAX(E_PERIOD_DATE) AS FY_OUTLOOK_PERIOD
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA"
    WHERE M_ACCOUNT_0 = ''Risk Weighted Assets''
    AND   T_REPORTING = ''FPNA'' AND DATA_TYPE = ''Outlook_PM''
    AND   T_VERSION = ''YTD'' AND MONTH_ABR = ''FY''
),
PERIOD_SET AS (
    SELECT P.CURRENT_YTD_PERIOD, P.CY_PQ_PERIOD, P.PY_PQ_PERIOD,
           P.YTD_PY_PERIOD, OA.FY_OUTLOOK_PERIOD
    FROM PERIODS P CROSS JOIN FY_OUTLOOK_ANCHOR OA
),
ALL_MEASURES AS (
    SELECT
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.CFX ELSE 0 END) AS YTD_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Budget''     AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.CFX ELSE 0 END) AS YTDB_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.CY_PQ_PERIOD       THEN A.CFX ELSE 0 END) AS CY_PQ_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Outlook_PM'' AND A.T_VERSION=''YTD'' AND A.MONTH_ABR=''FY'' AND A.E_PERIOD_DATE=PS.FY_OUTLOOK_PERIOD THEN A.CFX ELSE 0 END) AS FY_OUTLOOK_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''MTD'' AND A.E_PERIOD_DATE=PS.YTD_PY_PERIOD      THEN A.CFX ELSE 0 END) AS YTD_ACTUALS_PY_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.PY_PQ_PERIOD       THEN A.CFX ELSE 0 END) AS PY_PQ_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.RFX ELSE 0 END) AS YTD_ACTUALS_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Budget''     AND A.T_VERSION=''YTD'' AND A.E_PERIOD_DATE=PS.CURRENT_YTD_PERIOD THEN A.RFX ELSE 0 END) AS YTDB_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.CY_PQ_PERIOD       THEN A.RFX ELSE 0 END) AS CY_PQ_ACTUALS_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Outlook_PM'' AND A.T_VERSION=''YTD'' AND A.MONTH_ABR=''FY'' AND A.E_PERIOD_DATE=PS.FY_OUTLOOK_PERIOD THEN A.RFX ELSE 0 END) AS FY_OUTLOOK_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''MTD'' AND A.E_PERIOD_DATE=PS.YTD_PY_PERIOD      THEN A.RFX ELSE 0 END) AS YTD_ACTUALS_PY_RFX,
        SUM(CASE WHEN A.DATA_TYPE=''Actuals''    AND A.T_VERSION=''QTD'' AND A.E_PERIOD_DATE=PS.PY_PQ_PERIOD       THEN A.RFX ELSE 0 END) AS PY_PQ_ACTUALS_RFX
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA" A CROSS JOIN PERIOD_SET PS
    WHERE A.M_ACCOUNT_0 = ''Risk Weighted Assets'' AND A.T_REPORTING = ''FPNA''
    AND   A.E_PERIOD_DATE IN (PS.CURRENT_YTD_PERIOD,PS.CY_PQ_PERIOD,PS.PY_PQ_PERIOD,PS.YTD_PY_PERIOD,PS.FY_OUTLOOK_PERIOD)
)
SELECT
    M.YTD_ACTUALS_CFX,
    (M.YTD_ACTUALS_CFX   - M.YTDB_CFX)           AS VS_BUDGET_CFX,
    M.CY_PQ_ACTUALS_CFX,
    M.FY_OUTLOOK_CFX,
    (M.CY_PQ_ACTUALS_CFX - M.PY_PQ_ACTUALS_CFX)  AS VAR_PY_PQ_YOY_CFX,
    (M.YTD_ACTUALS_CFX   - M.YTD_ACTUALS_PY_CFX) AS VAR_YTD_PY_YOY_CFX,
    (M.FY_OUTLOOK_CFX    - M.YTD_ACTUALS_PY_CFX) AS VAR_FY_VS_PY_CFX,
    M.YTD_ACTUALS_RFX,
    (M.YTD_ACTUALS_RFX   - M.YTDB_RFX)           AS VS_BUDGET_RFX,
    M.CY_PQ_ACTUALS_RFX,
    M.FY_OUTLOOK_RFX,
    (M.CY_PQ_ACTUALS_RFX - M.PY_PQ_ACTUALS_RFX)  AS VAR_PY_PQ_YOY_RFX,
    (M.YTD_ACTUALS_RFX   - M.YTD_ACTUALS_PY_RFX) AS VAR_YTD_PY_YOY_RFX,
    (M.FY_OUTLOOK_RFX    - M.YTD_ACTUALS_PY_RFX) AS VAR_FY_VS_PY_RFX
FROM PERIOD_SET PS CROSS JOIN ALL_MEASURES M'
WHERE "ID" = 12;


-- ============================================================
-- INSERT 2 NEW CHART WIDGETS
-- ID 13: Income by Product  (bar chart — returns multiple rows)
-- ID 14: Income by Cluster  (bar chart — returns multiple rows)
-- ============================================================

-- ── INSERT ID=13: Income by Product ─────────────────────────────────

INSERT INTO "NRFP_FINANCIALS_REPORTINGMASTER" ("ID", "WIDGET", "QUERY")
VALUES (
13,
'Income by Product',
'WITH PERIODS AS (
    SELECT DISTINCT E_PERIOD_DATE
    FROM   T1NFRP_PHY."TBL_NFRP_DATE_CONFIG"
    WHERE  FILTER_DATE = ''CURRENT_MONTH'' AND FILTER_TYPE = ''PYR+CYR''
),
FILTERED_DATA AS (
    SELECT A.M_PRODUCT_CONCAT, A.DATA_TYPE, A.T_VERSION, A.MONTH_ABR, A.CFX, A.RFX
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA" A
    INNER JOIN PERIODS P ON A.E_PERIOD_DATE = P.E_PERIOD_DATE
    WHERE A.T_REPORTING = ''FPNA'' AND A.M_ACCOUNT_0 = ''Income''
    AND A.M_PRODUCT_0 IN (''Banking'', ''Markets'', ''Transaction services'')
    AND A.DATA_TYPE IN (''Actuals'', ''Outlook_PM'', ''Budget'') AND A.T_VERSION IN (''YTD'', ''MTD'')
),
ALL_MEASURES AS (
    SELECT F.M_PRODUCT_CONCAT,
        SUM(CASE WHEN F.DATA_TYPE = ''Actuals'' AND F.T_VERSION = ''YTD'' THEN F.CFX ELSE 0 END) AS YTD_CFX,
        SUM(CASE WHEN F.DATA_TYPE = ''Actuals'' AND F.T_VERSION = ''MTD'' THEN F.CFX ELSE 0 END) AS PY_YTD_CFX,
        SUM(CASE WHEN F.DATA_TYPE = ''Outlook_PM'' AND F.T_VERSION = ''YTD'' AND F.MONTH_ABR = ''FY'' THEN F.CFX ELSE 0 END) AS FY_OUTLOOK_CFX,
        SUM(CASE WHEN F.DATA_TYPE = ''Budget'' AND F.MONTH_ABR = ''FY'' THEN F.CFX ELSE 0 END) AS FY_BUDGET_CFX,
        SUM(CASE WHEN F.DATA_TYPE = ''Actuals'' AND F.T_VERSION = ''YTD'' THEN F.RFX ELSE 0 END) AS YTD_RFX,
        SUM(CASE WHEN F.DATA_TYPE = ''Actuals'' AND F.T_VERSION = ''MTD'' THEN F.RFX ELSE 0 END) AS PY_YTD_RFX,
        SUM(CASE WHEN F.DATA_TYPE = ''Outlook_PM'' AND F.T_VERSION = ''YTD'' AND F.MONTH_ABR = ''FY'' THEN F.RFX ELSE 0 END) AS FY_OUTLOOK_RFX,
        SUM(CASE WHEN F.DATA_TYPE = ''Budget'' AND F.MONTH_ABR = ''FY'' THEN F.RFX ELSE 0 END) AS FY_BUDGET_RFX
    FROM FILTERED_DATA F GROUP BY F.M_PRODUCT_CONCAT
)
SELECT M.M_PRODUCT_CONCAT,
    M.YTD_CFX, M.FY_OUTLOOK_CFX, M.FY_BUDGET_CFX,
    CASE WHEN M.FY_OUTLOOK_CFX < 0 THEN LEAST(M.FY_OUTLOOK_CFX, M.FY_BUDGET_CFX) ELSE GREATEST(M.FY_OUTLOOK_CFX, M.FY_BUDGET_CFX) END AS FY_OUTLOOK_BUDGET_CFX,
    CASE WHEN M.PY_YTD_CFX != 0 THEN ROUND((M.YTD_CFX - M.PY_YTD_CFX) * 100.0 / ABS(M.PY_YTD_CFX), 2) END AS YOY_PCT_CFX,
    M.YTD_RFX, M.FY_OUTLOOK_RFX, M.FY_BUDGET_RFX,
    CASE WHEN M.FY_OUTLOOK_RFX < 0 THEN LEAST(M.FY_OUTLOOK_RFX, M.FY_BUDGET_RFX) ELSE GREATEST(M.FY_OUTLOOK_RFX, M.FY_BUDGET_RFX) END AS FY_OUTLOOK_BUDGET_RFX,
    CASE WHEN M.PY_YTD_RFX != 0 THEN ROUND((M.YTD_RFX - M.PY_YTD_RFX) * 100.0 / ABS(M.PY_YTD_RFX), 2) END AS YOY_PCT_RFX
FROM ALL_MEASURES M ORDER BY M.M_PRODUCT_CONCAT'
);

-- ── INSERT ID=14: Income by Cluster ─────────────────────────────────

INSERT INTO "NRFP_FINANCIALS_REPORTINGMASTER" ("ID", "WIDGET", "QUERY")
VALUES (
14,
'Income by Cluster',
'WITH PERIODS AS (
    SELECT
        MAX(CASE WHEN D.ADD16 = ''0'' THEN D.E_PERIOD_DATE END) AS CURRENT_YTD_PERIOD,
        MAX(CASE WHEN D.ADD6 = ''PY_YTD'' THEN D.E_PERIOD_DATE END) AS YTD_PY_PERIOD,
        MAX(CASE WHEN D.ADD19 = ''CY'' THEN D.E_PERIOD_DATE END) AS FY_OUTLOOK_PERIOD,
        MAX(CASE WHEN D.ADD17 = ''1'' THEN D.E_PERIOD_DATE END) AS Q3_OUTLOOK_PERIOD
    FROM T1NFRP_PHY."TBL_NFRP_DATE_CONFIG" D
    WHERE D.FILTER_DATE = ''CURRENT_MONTH'' AND D.FILTER_TYPE = ''PYR+CYR''
),
ALL_MEASURES AS (
    SELECT A.M_PRODUCT_CONCAT,
        SUM(CASE WHEN A.DATA_TYPE = ''Actuals'' AND A.T_VERSION = ''YTD'' AND A.E_PERIOD_DATE = P.CURRENT_YTD_PERIOD THEN A.CFX ELSE 0 END) AS YTD_ACTUALS_CFX,
        SUM(CASE WHEN A.DATA_TYPE = ''Actuals'' AND A.T_VERSION = ''MTD'' AND A.E_PERIOD_DATE = P.YTD_PY_PERIOD THEN A.CFX ELSE 0 END) AS PY_YTD_ACTUALS_CFX,
        SUM(CASE WHEN A.E_PERIOD_DATE = P.FY_OUTLOOK_PERIOD AND MONTH_ABR = ''FY'' THEN A.CFX ELSE 0 END) AS FY_OUTLOOK_CFX,
        SUM(CASE WHEN A.DATA_TYPE = ''Outlook_PM'' AND A.T_VERSION = ''QTD'' AND A.E_PERIOD_DATE = P.Q3_OUTLOOK_PERIOD THEN A.CFX ELSE 0 END) AS Q3_OUTLOOK_CFX,
        SUM(CASE WHEN A.DATA_TYPE = ''Actuals'' AND A.T_VERSION = ''YTD'' AND A.E_PERIOD_DATE = P.CURRENT_YTD_PERIOD THEN A.RFX ELSE 0 END) AS YTD_ACTUALS_RFX,
        SUM(CASE WHEN A.DATA_TYPE = ''Actuals'' AND A.T_VERSION = ''MTD'' AND A.E_PERIOD_DATE = P.YTD_PY_PERIOD THEN A.RFX ELSE 0 END) AS PY_YTD_ACTUALS_RFX,
        SUM(CASE WHEN A.E_PERIOD_DATE = P.FY_OUTLOOK_PERIOD AND MONTH_ABR = ''FY'' THEN A.RFX ELSE 0 END) AS FY_OUTLOOK_RFX,
        SUM(CASE WHEN A.DATA_TYPE = ''Outlook_PM'' AND A.T_VERSION = ''QTD'' AND A.E_PERIOD_DATE = P.Q3_OUTLOOK_PERIOD THEN A.RFX ELSE 0 END) AS Q3_OUTLOOK_RFX
    FROM T1NFRP_PHY."CV_UP_NFRP_ALLDATA" A
    INNER JOIN PERIODS P ON A.E_PERIOD_DATE IN (P.CURRENT_YTD_PERIOD, P.YTD_PY_PERIOD, P.FY_OUTLOOK_PERIOD, P.Q3_OUTLOOK_PERIOD)
    WHERE A.T_REPORTING = ''FPNA'' AND A.M_ACCOUNT_0 = ''Income''
    GROUP BY A.M_PRODUCT_CONCAT
)
SELECT M.M_PRODUCT_CONCAT,
    M.YTD_ACTUALS_CFX, M.FY_OUTLOOK_CFX, M.Q3_OUTLOOK_CFX,
    CASE WHEN M.PY_YTD_ACTUALS_CFX != 0 THEN ROUND((M.YTD_ACTUALS_CFX - M.PY_YTD_ACTUALS_CFX) * 100.0 / ABS(M.PY_YTD_ACTUALS_CFX), 2) END AS YOY_PCT_CFX,
    M.YTD_ACTUALS_RFX, M.FY_OUTLOOK_RFX, M.Q3_OUTLOOK_RFX,
    CASE WHEN M.PY_YTD_ACTUALS_RFX != 0 THEN ROUND((M.YTD_ACTUALS_RFX - M.PY_YTD_ACTUALS_RFX) * 100.0 / ABS(M.PY_YTD_ACTUALS_RFX), 2) END AS YOY_PCT_RFX
FROM ALL_MEASURES M ORDER BY M.M_PRODUCT_CONCAT'
);

-- ── Verify ────────────────────────────────────────────────
SELECT "ID", "WIDGET", LENGTH("QUERY") AS QUERY_LEN
FROM "NRFP_FINANCIALS_REPORTINGMASTER"
ORDER BY "ID";